---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,message = FALSE,error = FALSE,
  comment = "#>"
)
```

# diagnosticos-pp 2023

<!-- badges: start -->
<!-- badges: end -->

## Carregando o banco de dados
```{r}
library(tidyverse)
saude <- readr::read_rds("data/saude.rds") %>% 
  dplyr::mutate(tipo = stringr::str_to_lower(tipo))
dplyr::glimpse(saude)
```

## Visualizando a série temporal
```{r}
saude %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic()
```

## Consumo de ultraprocessados
```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "ultra") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  ggplot2::coord_cartesian(ylim=c(.5,1))
```
```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "ultra") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  ggplot2::coord_cartesian(ylim=c(.5,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.5,.6,.025) )
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "ultra") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "ultra") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```



## Três refeições ao dia
```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "3r") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() # 
  #ggplot2::coord_cartesian(ylim=c(.5,1))
```


```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "3r") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.6,.7,.025),
                                label.x = rep(2017,5))
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "3r") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  #ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```
```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano < 2017) %>% 
  dplyr::filter(tipo == "3r") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  #ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "3r") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano < 2017) %>% 
  dplyr::filter(tipo == "3r") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2016` - `2015`)*100)
```
## Consumo de embutidos

```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "eb") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() #+ 
 # ggplot2::coord_cartesian(ylim=c(.5,1))
```


```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "eb") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.5,.6,.025),
                                label.x= rep(2016,5))
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "eb") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "eb") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```


## Feijão 

```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "feijao") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() #+ 
  #ggplot2::coord_cartesian(ylim=c(.5,1))
```
```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "feijao") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  ggplot2::coord_cartesian(ylim=c(.6,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.6,.7,.025),
                                label.x = rep(2017,5))
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "feijao") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "feijao") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```



## Frutas 
```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "frutas") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() #+ 
  #ggplot2::coord_cartesian(ylim=c(.5,1))
```


```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "frutas") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  ggplot2::coord_cartesian(ylim=c(.4,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.8,.9,.025),
                                label.x = rep(2017,5))
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "frutas") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "frutas") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```

## Guloseimas
```{r}
dplyr::glimpse(saude)  
saude %>% 
  dplyr::filter(tipo == "gl") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() #+ 
  #ggplot2::coord_cartesian(ylim=c(.5,1))
```
```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano <= 2019) %>% 
  dplyr::filter(tipo == "gl") %>% 
  ggplot2::ggplot(ggplot2::aes(x=ano,y=perc,color=id))+
  ggplot2::geom_point(shape=16,size=4) +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_color_viridis_d()+
  ggplot2::theme_classic() + 
  #ggplot2::coord_cartesian(ylim=c(.6,1))+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(label.y = seq(.42,.52,.025),
                                label.x = rep(2017,5))
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "gl") %>% 
  ggplot2::ggplot(ggplot2::aes(x=as.factor(ano),y=perc,fill=id))+
  #ggplot2::geom_col(position = "dodge")+
  ggplot2::geom_col(position="dodge",color="black") +
  # ggplot2::facet_wrap(~tipo,ncol=3)+
  ggplot2::scale_fill_viridis_d()+
  ggplot2::theme_classic() + 
  # ggplot2::coord_cartesian(ylim=c(.5,1)) +
  ggplot2::labs(x="Ano")
```

```{r}
dplyr::glimpse(saude)  
saude %>% dplyr::filter(ano > 2019) %>% 
  dplyr::filter(tipo == "gl") %>% 
  tidyr::pivot_wider(names_from = ano, values_from = perc,id_cols = id) %>% 
  dplyr::mutate(dif = (`2021` - `2020`)*100)
```

